# Generated by Django 3.0.7 on 2020-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('ifsc', models.CharField(db_column='ifsc', max_length=11, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(db_column='bank_id')),
                ('branch', models.CharField(db_column='branch', max_length=74)),
                ('address', models.CharField(db_column='address', max_length=195)),
                ('city', models.CharField(db_column='city', max_length=50)),
                ('district', models.CharField(db_column='district', max_length=50)),
                ('state', models.CharField(db_column='state', max_length=26)),
                ('bank_name', models.CharField(db_column='bank_name', max_length=49)),
            ],
            options={
                'db_table': 'bank_branches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=49)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('ifsc', models.CharField(db_column='ifsc', max_length=11, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(null=True)),
                ('branch', models.CharField(db_column='branch', max_length=74)),
                ('address', models.CharField(db_column='address', max_length=195)),
                ('city', models.CharField(db_column='city', max_length=50)),
                ('district', models.CharField(db_column='district', max_length=50)),
                ('state', models.CharField(db_column='state', max_length=26)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
    ]
